name = "Halton"
uuid = "99f3bb22-4f35-11e9-3a52-5dd37dc1f8e0"
authors = ["Nick Frazier <nfrazier@fdic.gov>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
